# constraints for SPI (PMOD1)

#set_property IOSTANDARD LVCMOS33 [get_ports {ss_n[0]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L15} [get_ports ss_n]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M15} [get_ports mosi]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L14} [get_ports miso]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M14} [get_ports sclk]




#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L13} [get_ports reset_n]

# constraint for LED pins (IO strip)
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M9} [get_ports {acc_x}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N9} [get_ports {acc_y}]
#set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M10} [get_ports {acc_z}]


set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_i[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_1/gpio_io_i[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_2/gpio_io_i[14]}]
set_property MARK_DEBUG true [get_nets design_1_i/pmod_accelerometer_a_0/miso]
set_property MARK_DEBUG true [get_nets design_1_i/pmod_accelerometer_a_0/mosi]

set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps7_0_axi_periph/S00_AXI_wdata[31]}]
set_property MARK_DEBUG true [get_nets design_1_i/pmod_accelerometer_a_0/clk]




set_property MARK_DEBUG false [get_nets {ss_n_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ss_n[0]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/ss_n[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axi_gpio_0/gpio_io_i[0]} {design_1_i/axi_gpio_0/gpio_io_i[1]} {design_1_i/axi_gpio_0/gpio_io_i[2]} {design_1_i/axi_gpio_0/gpio_io_i[3]} {design_1_i/axi_gpio_0/gpio_io_i[4]} {design_1_i/axi_gpio_0/gpio_io_i[5]} {design_1_i/axi_gpio_0/gpio_io_i[6]} {design_1_i/axi_gpio_0/gpio_io_i[7]} {design_1_i/axi_gpio_0/gpio_io_i[8]} {design_1_i/axi_gpio_0/gpio_io_i[9]} {design_1_i/axi_gpio_0/gpio_io_i[10]} {design_1_i/axi_gpio_0/gpio_io_i[11]} {design_1_i/axi_gpio_0/gpio_io_i[12]} {design_1_i/axi_gpio_0/gpio_io_i[13]} {design_1_i/axi_gpio_0/gpio_io_i[14]} {design_1_i/axi_gpio_0/gpio_io_i[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axi_gpio_1/gpio_io_i[0]} {design_1_i/axi_gpio_1/gpio_io_i[1]} {design_1_i/axi_gpio_1/gpio_io_i[2]} {design_1_i/axi_gpio_1/gpio_io_i[3]} {design_1_i/axi_gpio_1/gpio_io_i[4]} {design_1_i/axi_gpio_1/gpio_io_i[5]} {design_1_i/axi_gpio_1/gpio_io_i[6]} {design_1_i/axi_gpio_1/gpio_io_i[7]} {design_1_i/axi_gpio_1/gpio_io_i[8]} {design_1_i/axi_gpio_1/gpio_io_i[9]} {design_1_i/axi_gpio_1/gpio_io_i[10]} {design_1_i/axi_gpio_1/gpio_io_i[11]} {design_1_i/axi_gpio_1/gpio_io_i[12]} {design_1_i/axi_gpio_1/gpio_io_i[13]} {design_1_i/axi_gpio_1/gpio_io_i[14]} {design_1_i/axi_gpio_1/gpio_io_i[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/axi_gpio_2/gpio_io_i[0]} {design_1_i/axi_gpio_2/gpio_io_i[1]} {design_1_i/axi_gpio_2/gpio_io_i[2]} {design_1_i/axi_gpio_2/gpio_io_i[3]} {design_1_i/axi_gpio_2/gpio_io_i[4]} {design_1_i/axi_gpio_2/gpio_io_i[5]} {design_1_i/axi_gpio_2/gpio_io_i[6]} {design_1_i/axi_gpio_2/gpio_io_i[7]} {design_1_i/axi_gpio_2/gpio_io_i[8]} {design_1_i/axi_gpio_2/gpio_io_i[9]} {design_1_i/axi_gpio_2/gpio_io_i[10]} {design_1_i/axi_gpio_2/gpio_io_i[11]} {design_1_i/axi_gpio_2/gpio_io_i[12]} {design_1_i/axi_gpio_2/gpio_io_i[13]} {design_1_i/axi_gpio_2/gpio_io_i[14]} {design_1_i/axi_gpio_2/gpio_io_i[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/pmod_accelerometer_a_0/miso]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/pmod_accelerometer_a_0/mosi]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
